#- defaults:
#    link:
#      relink: true

- clean: ["~"]

- shell:
    # - git update-submodules # after linking ~/.gitconfig
    - [git submodule update --init --recursive, Installing submodules]

- link:
    ~/.config/.dotfiles:
      relink: true
      path: ""
    ~/.config/.zsh:
      relink: true
      path: "xdg_config/zsh"
    ~/.config/.localrc:
      relink: true
      path: "xdg_config/.localrc"
    ~/.config/.hushlogin:
      relink: true
      path: "xdg_config/.hushlogin"
    ~/.config/.editorconfig:
      relink: true
      path: "xdg_config/.editorconfig"
    ~/.config/.inputrc:
      relink: true
      path: "xdg_config/.inputrc"
    ~/.config/nvm:
      relink: true
      path: "xdg_config/nvm"
    ~/.config/.warp:
      relink: true
      path: "xdg_config/warp"
    ~/.config/.lazygit:
      relink: true
      path: "xdg_config/lazygit"
    ~/.config/nvim:
      relink: true
      path: "xdg_config/nvim"
    ~/.config/vim:
      relink: true
      path: "xdg_config/vim"
    ~/.config/git:
      relink: true
      path: "xdg_config/git"
    # ~/.config/.gitconfig:
    #   relink: true
    #   path: "xdg_config/git/.gitconfig"
    # ~/.config/.gitattributes:
    #   relink: true
    #   path: "xdg_config/git/.gitattributes"
    # ~/.config/.gitignore:
    #   relink: true
    #   path: "xdg_config/git/.gitignore_global"
    ~/.config/.cheatsheet:
      relink: true
      path: "misc/cheatsheet"
    ~/projects:
      relink: true
      path: "$PROJECTS"

- shell:
    # - git update-submodules # after linking ~/.gitconfig
    - [git submodule update --init --recursive, Installing submodules]
