#!/usr/bin/env zsh
set -e
source helpers.zsh

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
debug "  Detected BASEDIR=$BASEDIR"

# ########   #######  ######## ########   #######  ########
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ##     ## ##     ##    ##    ########  ##     ##    ##
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ########   #######     ##    ########   #######     ##

CONFIG=".install.conf.yaml"
DOTBOT_DIR="git-submodules/dotbot"
DOTBOT_BIN="bin/dotbot"

debug "  › cd ${BASEDIR}"
cd "${BASEDIR}"

info "  Update Dotbot git submodule dependencies"
debug "    › git -C '${DOTBOT_DIR}' submodule sync --quiet --recursive 2>&1"
if git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive 2>&1
then
  success "    Submodule sync successfull"
else
  fail "    Error while: Submodule sync"
fi

debug "    › git submodule update --init --recursive '${DOTBOT_DIR}'"
if git submodule update --init --recursive "${DOTBOT_DIR}" 2>&1
then
  success "    Submodule update successfull"
else
  fail "    Error while: Submodule update"
fi

info "  Start Dotbot..."
debug "    › '${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}' -d '${BASEDIR}' -c '${CONFIG}' '${@}'"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}" | info_stream

