#!/usr/bin/env zsh

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source helpers.zsh

#  ######  ########    ###    ########  ########
# ##    ##    ##      ## ##   ##     ##    ##
# ##          ##     ##   ##  ##     ##    ##
#  ######     ##    ##     ## ########     ##
#       ##    ##    ######### ##   ##      ##
# ##    ##    ##    ##     ## ##    ##     ##
#  ######     ##    ##     ## ##     ##    ##

# Ask for the administrator password upfront
# info "Get sudo"
if sudo -v 2>&1
then
  success "Got sudo"
else
  fail "Error getting sudo"
fi

# setup_gitconfig

# if setup_gitconfig 2>&1
# then
#   success "Git config setup done"
# else
#   fail "Error setting up git config"
# fi


# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# ########   #######  ######## ########   #######  ########
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ##     ## ##     ##    ##    ########  ##     ##    ##
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ########   #######     ##    ########   #######     ##
source ./install

# ##     ##    ###     ######      ######  ######## ##     ## ######## ########
# ###   ###   ## ##   ##    ##    ##    ##    ##    ##     ## ##       ##
# #### ####  ##   ##  ##          ##          ##    ##     ## ##       ##
# ## ### ## ##     ## ##           ######     ##    ##     ## ######   ######
# ##     ## ######### ##                ##    ##    ##     ## ##       ##
# ##     ## ##     ## ##    ##    ##    ##    ##    ##     ## ##       ##
# ##     ## ##     ##  ######      ######     ##     #######  ##       ##
# If we're on a Mac, let's install and setup other stuff.
if [ "$(uname -s)" = "Darwin" ]
then
  export DOTS=$XDG_CONFIG_HOME/.dotfiles

  #  #######   ######  ##     ##    ########  ######## ########    ###    ##     ## ##       ########  ######
  # ##     ## ##    ##  ##   ##     ##     ## ##       ##         ## ##   ##     ## ##          ##    ##    ##
  # ##     ## ##         ## ##      ##     ## ##       ##        ##   ##  ##     ## ##          ##    ##
  # ##     ##  ######     ###       ##     ## ######   ######   ##     ## ##     ## ##          ##     ######
  # ##     ##       ##   ## ##      ##     ## ##       ##       ######### ##     ## ##          ##          ##
  # ##     ## ##    ##  ##   ##     ##     ## ##       ##       ##     ## ##     ## ##          ##    ##    ##
  #  #######   ######  ##     ##    ########  ######## ##       ##     ##  #######  ########    ##     ######
  # info "Set OS X defaults"
  # if $DOTS/osx/set-defaults.sh 2>&1
  # then
  #   success "OS X defaults set"
  # else
  #   fail "Error setting OS X defaults"
  # fi
  # user "Note that some of these changes require a logout/restart to take effect."

  # #### ##    ##  ######  ########    ###    ##       ##           ######   #######  ######## ######## ##      ##    ###    ########  ########
  #  ##  ###   ## ##    ##    ##      ## ##   ##       ##          ##    ## ##     ## ##          ##    ##  ##  ##   ## ##   ##     ## ##
  #  ##  ####  ## ##          ##     ##   ##  ##       ##          ##       ##     ## ##          ##    ##  ##  ##  ##   ##  ##     ## ##
  #  ##  ## ## ##  ######     ##    ##     ## ##       ##           ######  ##     ## ######      ##    ##  ##  ## ##     ## ########  ######
  #  ##  ##  ####       ##    ##    ######### ##       ##                ## ##     ## ##          ##    ##  ##  ## ######### ##   ##   ##
  #  ##  ##   ### ##    ##    ##    ##     ## ##       ##          ##    ## ##     ## ##          ##    ##  ##  ## ##     ## ##    ##  ##
  # #### ##    ##  ######     ##    ##     ## ######## ########     ######   #######  ##          ##     ###  ###  ##     ## ##     ## ########
  info "Installing dependencies and software using $DOTS/script/install"
  if source $DOTS/zsh-setup-scripts/script/install  | info_stream #2>&1
  then
    success "Dependencies installed"
  else
    fail "Error installing dependencies"
  fi
fi

echo ''
success 'All installed!'
echo ''
