#!/usr/bin/env bash

# set -e

# ##     ## ######## ##       ########  ######## ########   ######
# ##     ## ##       ##       ##     ## ##       ##     ## ##    ##
# ##     ## ##       ##       ##     ## ##       ##     ## ##
# ######### ######   ##       ########  ######   ########   ######
# ##     ## ##       ##       ##        ##       ##   ##         ##
# ##     ## ##       ##       ##        ##       ##    ##  ##    ##
# ##     ## ######## ######## ##        ######## ##     ##  ######

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
  echo ''
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
  echo ''
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

#  ######  ########    ###    ########  ########
# ##    ##    ##      ## ##   ##     ##    ##
# ##          ##     ##   ##  ##     ##    ##
#  ######     ##    ##     ## ########     ##
#       ##    ##    ######### ##   ##      ##
# ##    ##    ##    ##     ## ##    ##     ##
#  ######     ##    ##     ## ##     ##    ##

# Ask for the administrator password upfront
echo ''
info "Get sudo"
if sudo -v 2>&1
then
  success "Got sudo"
else
  fail "Error getting sudo"
fi

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# ########   #######  ######## ########   #######  ########
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ##     ## ##     ##    ##    ########  ##     ##    ##
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ########   #######     ##    ########   #######     ##

CONFIG=".install.conf.yaml"
DOTBOT_DIR=".dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

info "Update Dotbot git submodule dependencies"
# git submodule update --init --recursive "${DOTBOT_DIR}"
if git submodule update --init --recursive "${DOTBOT_DIR}" 2>&1
then
  success "Update successfull"
else
  fail "Error while updating"
fi

info "Start Dotbot"
echo ''
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
echo ''
success "Dotbot finished"


# ##     ##    ###     ######      ######  ######## ##     ## ######## ########
# ###   ###   ## ##   ##    ##    ##    ##    ##    ##     ## ##       ##
# #### ####  ##   ##  ##          ##          ##    ##     ## ##       ##
# ## ### ## ##     ## ##           ######     ##    ##     ## ######   ######
# ##     ## ######### ##                ##    ##    ##     ## ##       ##
# ##     ## ##     ## ##    ##    ##    ##    ##    ##     ## ##       ##
# ##     ## ##     ##  ######      ######     ##     #######  ##       ##
# If we're on a Mac, let's install and setup other stuff.
if [ "$(uname -s)" == "Darwin" ]
then
    export DOTS=$HOME/.dotfiles

  #  #######   ######  ##     ##    ########  ######## ########    ###    ##     ## ##       ########  ######
  # ##     ## ##    ##  ##   ##     ##     ## ##       ##         ## ##   ##     ## ##          ##    ##    ##
  # ##     ## ##         ## ##      ##     ## ##       ##        ##   ##  ##     ## ##          ##    ##
  # ##     ##  ######     ###       ##     ## ######   ######   ##     ## ##     ## ##          ##     ######
  # ##     ##       ##   ## ##      ##     ## ##       ##       ######### ##     ## ##          ##          ##
  # ##     ## ##    ##  ##   ##     ##     ## ##       ##       ##     ## ##     ## ##          ##    ##    ##
  #  #######   ######  ##     ##    ########  ######## ##       ##     ##  #######  ########    ##     ######
  info "Set OS X defaults"

  echo ''
  if $DOTS/osx/set-defaults.sh 2>&1
  echo ''

  then
    success "OS X defaults set"
  else
    fail "Error setting OS X defaults"
  fi
  user "Note that some of these changes require a logout/restart to take effect."

  # ##     ##  #######  ##     ## ######## ########  ########  ######## ##      ##
  # ##     ## ##     ## ###   ### ##       ##     ## ##     ## ##       ##  ##  ##
  # ##     ## ##     ## #### #### ##       ##     ## ##     ## ##       ##  ##  ##
  # ######### ##     ## ## ### ## ######   ########  ########  ######   ##  ##  ##
  # ##     ## ##     ## ##     ## ##       ##     ## ##   ##   ##       ##  ##  ##
  # ##     ## ##     ## ##     ## ##       ##     ## ##    ##  ##       ##  ##  ##
  # ##     ##  #######  ##     ## ######## ########  ##     ## ########  ###  ###
  if ! which brew > /dev/null; then
    info "Installing homebrew"
    echo ''
    $DOTS/homebrew/install-homebrew.sh 2>&1
    echo ''
    success "Homebrew installed"
  else
    success "Homebrew already installed"
  fi;

  # #### ##    ##  ######  ########    ###    ##       ##           ######   #######  ######## ######## ##      ##    ###    ########  ########
  #  ##  ###   ## ##    ##    ##      ## ##   ##       ##          ##    ## ##     ## ##          ##    ##  ##  ##   ## ##   ##     ## ##
  #  ##  ####  ## ##          ##     ##   ##  ##       ##          ##       ##     ## ##          ##    ##  ##  ##  ##   ##  ##     ## ##
  #  ##  ## ## ##  ######     ##    ##     ## ##       ##           ######  ##     ## ######      ##    ##  ##  ## ##     ## ########  ######
  #  ##  ##  ####       ##    ##    ######### ##       ##                ## ##     ## ##          ##    ##  ##  ## ######### ##   ##   ##
  #  ##  ##   ### ##    ##    ##    ##     ## ##       ##          ##    ## ##     ## ##          ##    ##  ##  ## ##     ## ##    ##  ##
  # #### ##    ##  ######     ##    ##     ## ######## ########     ######   #######  ##          ##     ###  ###  ##     ## ##     ## ########
  info "Installing dependencies and software using $DOTS/script/install"
  if source $DOTS/script/install 2>&1
  then
    success "Dependencies installed"
  else
    fail "Error installing dependencies"
  fi
fi

echo ''
success 'All installed!'
echo ''
