#!/usr/bin/env zsh
set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source helpers.zsh

# ########   #######  ######## ########   #######  ########
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ##     ## ##     ##    ##    ########  ##     ##    ##
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ##     ## ##     ##    ##    ##     ## ##     ##    ##
# ########   #######     ##    ########   #######     ##

CONFIG=".install.conf.yaml"
DOTBOT_DIR="git-submodules/dotbot"
DOTBOT_BIN="bin/dotbot"

info "Update Dotbot git submodule dependencies"
info "cd ${BASEDIR}"
cd "${BASEDIR}"

info "git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive 2>&1"
if git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive 2>&1
then
  success "Submodule sync successfull"
else
  fail "Error while: Submodule sync"
fi

if git submodule update --init --recursive "${DOTBOT_DIR}" 2>&1
then
  success "Submodule update successfull"
else
  fail "Error while: Submodule update"
fi

info "Start Dotbot"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}" | info_stream
success "Dotbot finished"
