#!/usr/bin/env zsh
source helpers.zsh
src "$(basename "${(%):-%x}")"

CONFIG="dotbot.conf.yaml"
DOTBOT_DIR="git-submodules/dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

debug "Changing directory to ${BASEDIR}"
cd "${BASEDIR}"

# Sync Dotbot submodule
user "Updating Dotbot submodule..."
if git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive; then
  success "  ✓ Dotbot submodule sync successful"
else
  fail "  ✗ Dotbot submodule sync failed"
fi

# Update Dotbot submodule
if git submodule update --init --recursive "${DOTBOT_DIR}"; then
  success "  ✓ Dotbot submodule update successful"
else
  fail "  ✗ Dotbot submodule update failed"
fi

# Run Dotbot
user "Starting Dotbot..."
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "$@" | info_stream
