#!/usr/bin/env zsh
src "$(basename "${(%):-%x}")"

# Run all dotfiles installers.

user "Searching for installers..."
installers=($(find . -name install.sh))

if [[ ${#installers[@]} -eq 0 ]]; then
  warn " ! No installers found."
  exit 0
fi

info "Found ${#installers[@]} installers. Executing..."

for installer in "${installers[@]}"; do
  info "  › Running ${installer}..."
  if sh -c "$installer"; then
    success "  ✓ ${installer} completed successfully."
  else
    fail "  ✗ ${installer} failed."
  fi
done

success "All installers finished!"
exit 0
