#!/usr/bin/env bash
#
# Run all dotfiles installers.
set -e

# cd "$(dirname $0)"/..

debug "  find the installers and run them iteratively..."
find . -name install.sh | while read installer ; do debug '    Found installer '${installer}; done
log_info "  Starting installers..."
find . -name install.sh | while read installer ; do log_info '    › '${installer}; sh -c "${installer}"; done
