#!/usr/bin/env zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c holm<tab>/bo<tab>
#
# ...to quickly jump into holman/boom, for example.

c() {
    # if [[ -z "$PROJECTS" ]]; then
    #   if command -v log_fatal > /dev/null; then
    #     l_always log_fatal "Error: \$PROJECTS environment variable is not set"
    #   else
    #     echo "Error: \$PROJECTS environment variable is not set" >&2
    #   fi
    #   return 1
    # fi

    if [[ -z "$1" ]]; then
    echo "Usage: c <project-name>"
    return 1
    fi

    cd "$PROJECTS/$1"
}
