#!/usr/bin/env bash
#
# Run all dotfiles installers.

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
  echo ''
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
  echo ''
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

set -e

# cd "$(dirname $0)"/..

# find the installers and run them iteratively
echo ''
find . -name install.sh | while read installer ; do info 'Found installer '${installer}; done
info "Starting installers"
find . -name install.sh | while read installer ; do echo ''; info 'Running '${installer}; echo ''; sh -c "${installer}"; echo ''; user ${installer}; done
