cask_args appdir: '/Applications'

#############################################
# Minimal Brewfile for setting up a new Mac #
#############################################

tap 'felixkratz/formulae'       # For Sketchybar
tap 'koekeishiya/formulae'      # For Yabai
tap 'sandertammesoo/formulae'   # For Yabai
brew 'mas'                      # Apple's Mac App Store CLI

#  Cask-Update tool that works with brew cask to update all of your Mac apps. To upgrade all of you Mac apps, just do: brew cu
# Cask-Update details some other features. In particular, I like brew cu pin <caskname> which locks an app to a specific version.
tap "buo/cask-upgrade" # Cask-Update tap

# Version Control
brew 'git'
brew 'git-flow'
brew 'grc'
brew 'gnupg'

# CLI Utils
brew 'coreutils'    # GNU File, Shell, and Text utilities https://www.gnu.org/software/coreutils
brew 'moreutils'    # Collection of tools that nobody wrote when UNIX was young https://joeyh.name/code/moreutils/
brew 'findutils'    # Collection of GNU find, xargs, and locate https://www.gnu.org/software/findutils/
brew 'diffutils'    # GNU diff utilities https://www.gnu.org/software/diffutils/
brew 'grep'         # GNU grep, egrep and fgrep https://www.gnu.org/software/grep/
brew 'ack'          # Search tool like grep, but optimized for programmers https://beyondgrep.com/
brew 'tree'         # Display directories as trees (with optional color/HTML output) https://oldmanprogrammer.net/source.php?dir=projects/tree
brew 'wget'         # Internet file retriever https://www.gnu.org/software/wget/
brew "htop"         # Improved top (interactive process viewer) https://htop.dev/
brew "jq"           # Lightweight and flexible command-line JSON processor https://jqlang.github.io/jq/
# brew 'gnu-sed', args: ['with-default-names'] # GNU implementation of the famous stream editor https://www.gnu.org/software/sed/
brew 'fzf'          # Command-line fuzzy finder
brew 'cheat'       # Create and view interactive cheatsheets on the command-line
brew 'gpg'         # GNU Privacy Guard https://gnupg.org/
brew 'starship'     # The minimal, blazing-fast, and infinitely customizable prompt for any shell https://starship.rs/
brew 'superfile'    # A modern replacement for 'ls'
brew 'bat'         # A cat(1) clone with syntax highlighting and Git integration
brew 'fd'          # A simple, fast and user-friendly alternative to 'find'
brew 'ripgrep'     # A line-oriented search tool that recursively searches your current directory for a regex pattern
brew 'tldr'        # Simplified and community-driven man pages
# cask 'ngrok'       # Secure introspectable tunnels to localhost https://ngrok.com/
brew 'zoxide'     # A smarter cd command. Supports fuzzy searching.
brew 'nmap'         # Port scanning utility for large networks https://nmap.org/
brew 'stow'        # Symlink farm manager https://www.gnu.org/software/stow/
brew 'wifi-password'# Show the current WiFi network password https://github.com/rauchg/wifi-password
brew 'macmon'    # Sudoless performance monitoring for Apple Silicon processors https://github.com/vladkens/macmon
brew 'eza'         # A modern replacement for 'ls'

cask "font-hack-nerd-font"              # Developer targeted fonts with a high number of glyphs
cask "font-sf-pro"                      # Sans-serif variant of "San Francisco" by Apple
cask "sf-symbols"

# MacOS Enhancements and Utilities - Installed with setup scripts
# brew "felixkratz/formulae/sketchybar"   # Custom macOS statusbar with shell plugin, interaction and graph support https://github.com/FelixKratz/SketchyBar
# brew "koekeishiya/formulae/skhd"        # Simple hotkey-daemon for macOS. https://github.com/koekeishiya/skhd
# brew "koekeishiya/formulae/yabai"       # A tiling window manager for macOS based on binary space partitioning. https://github.com/koekeishiya/yabai


######################
###### GUI Apps ######
######################

# Browsers
cask 'brave-browser'
# cask 'microsoft-edge'
# cask 'firefox'
# cask 'google-chrome'

# Messangers & other communication
cask 'slack'
cask 'messenger'
cask 'signal'
cask 'discord'
cask 'zoom'
cask "mattermost"

# Video players & music
cask 'spotify'
# cask 'vlc'
cask 'iina'

# Quality of life and productivity applications
cask '1password'    # Password manager
cask 'alfred'       # Better Spotlight replacement
# cask 'freedom'      # Block apps and webcontet to focus on deep work
cask 'loom'         # Screen recorder

# Networking Applications
cask 'nordvpn'      # VPN
brew "openvpn"
# cask 'transmission'
# cask 'tunnelbear'

# Other Applications
cask "warp"
cask 'notion'
cask 'airtable'
cask 'shottr'       # Screenshot application
cask 'hiddenbar'    # Bartender like app to hide 'trayicons'
cask "alt-tab"
cask "elgato-stream-deck"
cask "elgato-wave-link"
# cask "figma"
cask "google-drive"
cask "home-assistant"
cask "hyperkey"
cask "keymapp"
cask "logi-options+"
# cask 'tempbox'    # Temporary email inbox
# cask 'steam'
# cask 'parallels'

mas "1Password for Safari", id: 1569813296
mas "DigiDoc4 Client", id: 1370791134
#mas "Gemini 2", id: 1090488118
mas "Numbers", id: 409203825
mas "Parcel", id: 639968404
mas "Timer RH", id: 929960914
mas "Web eID", id: 1576665083



#########################
### Development Tools ###
#########################

# Software Development & Environment control
# https://github.com/jesseduffield/lazygit
# https://www.youtube.com/watch?v=CPLdltN7wgE
# https://github.com/akinsho/toggleterm.nvim#custom-terminal-usage
cask 'visual-studio-code'
cask 'devtoys' # https://github.com/ObuchiYuki/DevToysMac
cask "insomnia"

brew 'go'           # needed for lazygit
brew 'lazygit'      # Simple terminal UI for git commands https://github.com/jesseduffield/lazygit/
brew 'lazydocker'   # Lazier way to manage everything docker https://github.com/jesseduffield/lazydocker
brew 'lazyssh'     # Simple terminal UI for ssh https://github.com/Adembc/lazyssh
brew 'jqp'        # JSON query tool https://github.com/noahgorstein/jqp
cask 'dbeaver-community'  # Universal database tool and SQL client

brew 'pyenv'        # Python version management https://github.com/pyenv/pyenv
# brew 'uncrustify'
# brew 'gh'
# brew 'node'
# cask 'atom'
# cask 'cocoapods'
# brew 'jenv'
# brew 'rbenv'
# brew 'npm'
# brew 'nvm'
# brew 'yarn'
# brew 'docker'
# brew 'postgresql'
# brew 'libgit2'
# brew 'openssl'
# cask 'gcc-arm-embedded'
# brew "jupyterlab"

##################
# Miscellaneous #
##################
# brew "ata"          # Ask the Terminal Anything - chat GPT in terminal
# brew "c2048"        # 2048 game
# brew "mailsy"       # Quickly generate a temporary email address https://github.com/BalliAsghar/Mailsy
# brew "wifi-password"# Show the current WiFi network password https://github.com/rauchg/wifi-password
# brew 'youtubedr'    # Download Youtube Video in Golang https://github.com/kkdai/youtube

# brew "ansible"      # Automate app deployment, configuration management and orchestration https://www.ansible.com/
# brew "c2048"        # 2048 game
