# all of our .bash files
# load the path files
for file in $HOME/.dotfiles/**/{bash_prompt,exports,aliases,functions,extra,completion,path,setup}.bash
do
    # [ -r $file ] && [ -f $file ] && source $file && echo $file;
    [ -r $file ] && [ -f $file ] && source $file;
done;

for file in $HOME/.dotfiles/system/{bash_prompt,exports,aliases,functions,extra,completion,path,setup}.bash
do
    # [ -r $file ] && [ -f $file ] && source $file && echo $file;
    [ -r $file ] && [ -f $file ] && source $file;
done;

unset file;

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/sandert/.sdkman"
[[ -s "/Users/sandert/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/sandert/.sdkman/bin/sdkman-init.sh"
