
# Stash your environment variables in .localrc files. This means they'll stay out
# of your main dotfiles repository (which may be public, like this one), but
# you'll have access to them in your scripts.
# Allow local customizations in the ~/.bashrc_local_before file
if [ -f ~/.bashrc_local_before ]; then
    source ~/.bashrc_local_before
fi

# External plugins (initialized before)
# source ~/.bash/plugins_before.bash

[ -n "$PS1" ] && source ~/.bash_profile;

# External plugins (initialized after)
# source ~/.bash/plugins_after.bash

# Allow local customizations in the ~/.bashrc_local_after file
if [ -f ~/.bashrc_local_after ]; then
    source ~/.bashrc_local_after
fi
