#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

FONT_FACE="JetBrainsMono Nerd Font"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  height=37
  blur_radius=30
  position=bottom
  sticky=off
  padding_left=10
  padding_right=10
  color=$BAR_COLOR_SEC
  #color=#15ffffff
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

# icon.font="Hack Nerd Font:Bold:17.0"
# label.font="Hack Nerd Font:Bold:14.0"
# icon.font="SF Pro:Semibold:15.0"
# label.font="SF Pro:Semibold:15.0"

default=(
  icon.color=$WHITE
  label.color=$WHITE
  icon.font="$FONT_FACE:Bold:16.0"
  label.font="$FONT_FACE:Semibold:15.0"
  background.color=$ITEM_BG_COLOR_SEC
  background.corner_radius=5
  background.height=24
  padding_left=5
  padding_right=5
  label.padding_left=4
  label.padding_right=10
  icon.padding_left=10
  icon.padding_right=4
)

sketchybar --default "${default[@]}"

##### Display Orientation Detection #####
# Build LANDSCAPE_DISPLAYS: array of sketchybar arrangement-ids for non-portrait displays.
# Items too wide for portrait are added once per landscape display using display=N.
LANDSCAPE_DISPLAYS=()
while IFS= read -r _d; do
  _arr=$(printf '%s' "$_d" | jq -r '."arrangement-id"')
  _portrait=$(printf '%s' "$_d" | jq '(.frame.w < .frame.h)')
  [[ "$_portrait" == "true" ]] && continue
  LANDSCAPE_DISPLAYS+=("$_arr")
done < <(sketchybar --query displays | jq -c '.[]')

##### Adding Left Items #####
# We add some regular items to the left side of the bar
# only the properties deviating from the current defaults need to be set
source $ITEM_DIR/spaces.sh

# -- Center Items --
#source $ITEM_DIR/media.sh
source $ITEM_DIR/front_app.sh

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events
#source $ITEM_DIR/calendar.sh
#source $ITEM_DIR/displays.sh
source $ITEM_DIR/volume.sh
#source $ITEM_DIR/battery.sh
#source $ITEM_DIR/cpu.sh
source $ITEM_DIR/space_yabai_mode.sh
source $ITEM_DIR/skhd_mode.sh
source $ITEM_DIR/claude_limits.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
